# https://doc.qt.io/qt-6/macos.html
c_stdlib_version:
  - 15.2           # [osx]
  - 2022.12        # [win]
OSX_SDK_VER:       # [osx]
  - 15             # [osx]

# https://doc.qt.io/qt-6/windows.html
c_compiler:    # [win]
  - vs2022     # [win]
cxx_compiler:  # [win]
  - vs2022     # [win]

# XCode 15.0 came with SDK 14.0 and clang 15
# https://en.wikipedia.org/wiki/Xcode
c_compiler_version:
  - 20                 # [osx]
  # - 11                 # [linux]
cxx_compiler_version:
  - 20                 # [osx]
  # - 11                 # [linux]

# Have to leave this for now or else the overlinking checks fail when we revert back to the aggregate CBC and use the
# 12.1 sysroot.
CONDA_BUILD_SYSROOT:
  - /Library/Developer/CommandLineTools/SDKs/MacOSX15.sdk  # [osx and arm64]
